language: node_js
node_js:
- "node"
cache:
  directories:
    - "node_modules"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/940a538b235ec98d7546
    on_success: always
    on_failure: always
    on_start: always
